name: Build
on:
 pull_request:
   branches:
     - main
     - develop
jobs:
  # sonarcloud:
  #   name: SonarCloud
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0 
  #     - name: Install dependencies
  #       run: yarn
  #     - name: Test and coverage
  #       run: yarn test:all
  #     - name: SonarCloud Scan
  #       uses: SonarSource/sonarcloud-github-action@master
  #       env:
  #         GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  #         SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
  get_metrics:
    # needs: sonarcloud
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Get metrics and commit
      run: |
        mkdir analytics-raw-data
        url="https://sonarcloud.io/api/measures/component?component=${{secrets.PROJECT_KEY}}&metricKeys=files,functions,complexity,comment_lines_density,duplicated_lines_density,coverage,ncloc,tests,test_errors,test_failures,test_execution_time,security_rating&pullRequest=${{github.event.pull_request.number}}"
        echo $url
        curl $(echo $url | tr -d \') > analytics-raw-data/fga-eps-mds-2022-1-Alectrion-FrontEnd-$(date +'%m-%d-%Y-%H-%M-%S')-${{github.event.pull_request.number}}.json
    - name: push metrics
      run: |
        git config --global user.email "${{secrets.GIT_USER_EMAIL}}"
        git config --global user.name "${{secrets.GIT_USER_NAME}}"
        git clone --single-branch --branch main "https://x-access-token:${{secrets.API_TOKEN_GITHUB}}@github.com/fga-eps-mds/2022-1-Alectrion-DOC" 2022-1-Alectrion-DOC
        cp -R analytics-raw-data/*.json 2022-1-Alectrion-DOC/analytics-raw-data/
        cd 2022-1-Alectrion-DOC
        git add .
        git commit -m "doc: adiciona metricas do ${{ github.event.repository.name }} PR #${{github.event.pull_request.number}}"
        git push